const exceptionLogger = {
    logError: (exception) => {
        throw exception;
    }
};

export { exceptionLogger };